config/routes.rb
Rails.application.routes.draw do
  resources :favourites, only: [:index, :new, :create]
  get 'movies/search', as: :movie_search
  get 'movies/show'
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index
    @favourites = Favourite.all
  end

  def new
    @favourite = Favourite.new
  end

  def create
    @favourite = Favourite.new(favourite_params)
    if @favourite.save
      redirect_to favourites_path, notice: 'Favourite was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @favourite.destroy
    redirect_to favourites_url, notice: 'Favourite was successfully destroyed.'
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def favourite_params
    params.require(:favourite).permit(:title, :url)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def search
    if params[:q]
      @movies = request_movies_from_omdb
    end
  end

  def show
  end

  private

  def request_movies_from_omdb
    url = omdb_url
    response = request_movies(url)
    JSON.parse(response.body)['Search']
  end

  def request_movies(url)
    Net::HTTP.new(url.host, url.port).get(url)
  end

  def omdb_url
    URI.parse("http://www.omdbapi.com/?s=#{params[:q]}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Favourites</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favourites.each do |favourite| %>
      <tr>
        <td><%= favourite.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to search', movie_search_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/search.html.erb
<%= form_tag(movie_search_path, method: :get) do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<% if @movies.present? %>
  <h1>Movies Found</h1>
  <ul>
    <% @movies.each do |movie| %>

      <%= form_for Favourite.new, url: {action: "create", controller: "favourites", remote: true} do |f| %>
        <li><%= movie['Title'] %></li>
        <%= hidden_field(:favourite, :title, :value => movie['Title']) %>
        <%= f.submit "Add to favourites" %>
      <% end %>

    <% end %>
  </ul>
  <p><%= link_to('Search again', movie_search_path) %></p>
<% end %>

app/views/movies/show.html.erb
<h1>Movies Found</h1>
<ul>
  <% @movies.each do |movie| %>

    <%= form_for Favourite.new, url: {action: "create", controller: "favourites", remote: true} do |f| %>
      <li><%= movie['Title'] %></li>
      <%= hidden_field(:favourite, :title, :value => movie['Title']) %>
      <%= f.submit "Add to favourites" %>
    <% end %>

  <% end %>
</ul>
<p><%= link_to('Search again', movie_search_path) %></p>